# Recreated on every launch. Persistent game data lives under worlds/.
allow-flight=false
difficulty=easy
enable-command-block=false
enable-rcon=false
enforce-whitelist=false
gamemode=survival
generate-structures=true
hardcore=false
level-name=world
max-players=10
motd=Fred and Luke Land
online-mode=true
pvp=true
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=16
view-distance=10
white-list=false
